name: My First Workflow

on: push

jobs: 
   first_job:
       runs-on: ubuntu-latest
       steps:
       - name: welcome massage
         run: echo "This is my first job"

       - name: list files
         run: ls